### ISSUE TITLE
Custom Bar Groups Not Functioning as Expected

### ISSUE THREAD

**Issue by madtempest** [Dicebar/raven-old#12] opened 2022-11-01 13:11 UTC
I have a few custom bar groups to help me identify when some buffs or debuffs are expiring such as Icebound Fortitude, or to count stacks of and timers such as Bursting. (For context, I was using Raven already for buff/debuffs and it made more sense to do this than the CPU impact of using WeakAuras to do it)

These custom bar groups do one of two things:
1) They don't render at all; or
2) They render their first frame and then freeze.

I have disabled all other addons and confirmed that this does not change the behaviour of the rendering.

I appreciate you looking into this.

**Comment by dorana** [comment] 2022-11-01 16:15
I'll check up on this. Thanks for reporting

**Comment by dorana** [comment] 2022-11-02 09:17
I have been unable to recreate this in the latest version of the Addon.
I created a custom Bar for a buff, in this case Acquired Sword, since it's part of the trinket Cache of Acquired Treasure that rotates between 3 buffs.

I tested some effects to this like pulse for when it activates and sparkle when it finishes, this buff shows up on each rotation of this buff.

If the issue remains with the latest version please let me know, else I will close this ticket in 48h

**Comment by madtempest** [comment] 2022-11-02 12:59
Hi, 

I was testing with the Nov 1 version of the addon. The only other condition might be that my custom bars are pre-existing to the newer versions.

I don't have time in the next 24 hours to test, but I will try to create a new custom bar group with the same parameters as my existing ones and see if I can get it working or the behaviour replicates.

Thanks.

**Comment by dorana** [comment] 2022-11-02 13:56
Thank you, please report your findings, I will keep the Issue open until such time

**Comment by madtempest** [comment] 2022-11-03 09:09
Hi,

So I have managed to test with a fresh Raven.lua and the problem does not appear to occur with a custom bar meaning there is something in my existing Raven.lua that is corrupt/not compatible.

I'm going to see what I can do to combine the two into a third one so I can keep as much of my config/layout as before but I would ask, has anything changed in the structure of the LUA file at all?

**Comment by dorana** [comment] 2022-11-03 09:42
Not in the structure itself, the changes for the Dragonflight UI has been focused on bugfixes for events, such as Cancel buffs etc, as well as that the Ace3 library that handles the Options window elements have been updated.
I did not have any Custom bars set up in my own setup previously, I mainly work with Autobars and spell lists.

However we do want so that the configurations made prior to the new changes would work after update ofc.

**Comment by Dicebar** [comment] 2022-11-03 09:47
Yesterday I created a new character and found that one of the conditions in my custom bars was missing the "Target" selection (player, target, focus, etc). Normally one is always selected, so I suspect some data corruption might be at play. It could simply be bugs in the stored data that were introduced while the addon was bugged, and that the problem is already resolved. But it could also be  an active bug to look into.

I haven't tried to narrow this down yet, though. I'll put some work into this over the weekend.

**Comment by madtempest** [comment] 2022-11-03 09:53
Did you want me to upload a copy of my existing LUA file?

I did try to combine the files but I got the same issue leading me to believe you're correct about data corruption in my existing LUA file.

I'm wondering if creating a new profile on the old LUA file will fix it (not sure why I didn't do this in the first place sorry). I'll give that a go and if you want a copy of my original LUA file I'm happy to provide it.

**Comment by Dicebar** [comment] 2022-11-03 10:05
I use custom bars extensively myself, so I think my own profile should do the trick. But if you want to upload the original file it's great to have one that we can be certain of will bug every time. Thanks!

**Comment by madtempest** [comment] 2022-11-03 10:53
[Raven.zip](https://github.com/Dicebar/raven/files/9927631/Raven.zip)

**Comment by madtempest** [comment] 2022-11-03 11:44
Creating a new profile didnt work, but creating the custom bars again from scratch without any profile has worked.

**Comment by dorana** [comment] 2022-11-03 11:51
Thank you. I think dicebar is currently looking into the changes to profile saves changes with the new ace lib version

**Comment by Dicebar** [comment] 2022-11-09 13:53
I think this issue was caused by #9, which has now been fixed. Could you check if everything works properly now? Thanks!

**Comment by Dicebar** [comment] 2022-11-12 13:23
The addon has moved to a new repo, and we're doing official releases now through CurseForge!

If this problem hasn't been resolved, please create a new issue [here](https://github.com/Dicebar/Raven/issues). Thanks!

**Closed by Dicebar** 2022-11-12 13:23 UTC
Labels: bug, question, live
